apiVersion: batch.rener.med.one/v1
kind: CronJob
metadata:
  name: example
  namespace: default
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: demo
              image: busybox
              args:
                - /bin/sh
                - -c
                - "date; echo Hello from the CronJob"
          restartPolicy: OnFailure

